name: Utils
author: GiverPlay007
version: 1.1.1
load: POSTWORLD
description: Plugin feito da forma mais simples possivel...
api-version: 1.15
main: me.giverplay.agaragun.Main
commands:
  tpa:
  tpaceitar:
  tpanegar:
  lixo:
    aliases: ['lixeira']
  local:
    aliases: ['l']
  bypass:
    aliases: ['cmdbypass']
  reiniciar:
    aliases: ['restart']